#!/bin/sh

./select_classes_by_accuracies.py \
        --accuracy_path /Users/kumada/Data/image_net/accuracies_for_all_classes.txt \
        --lower_accuracy 0.5 \
        --input_dir_path /Users/kumada/Data/image_net/selected_images_256_greater_than_200_images \
        --mode select \
        --output_dir_path /Users/kumada/Data/image_net/selected_images_256_by_accuracies

 
