#!/bin/sh

./train.py \
    --initial_model_path /Users/kumada/Data/image_net/bvlc_reference_caffenet-2017-01-08.pkl \
    --training_data_path /Users/kumada/Data/image_net/selected_images_256/train_valid.txt \
    --testing_data_path  /Users/kumada/Data/image_net/selected_images_256/test.txt \
    --mean_image_path    /Users/kumada/Data/image_net/ilsvrc_2012_mean.npy
