#!/bin/sh

./create_list.py \
        --src_dir    /Volumes/TOSHIBA\ EXT/mac/image_net/selected_images_256_greater_than_200_images \
        --label_path /Volumes/TOSHIBA\ EXT/mac/image_net/selected_images_256_greater_than_200_images/label.txt
