#!/bin/sh

./preprocess_data.py \
    --mean_image_path /Users/kumada/Data/image_net/ilsvrc_2012_mean.npy \
    --input_dir_path  /Volumes/TOSHIBA\ EXT/mac/image_net/test/inputs \
    --output_dir_path /Volumes/TOSHIBA\ EXT/mac/image_net/test/outputs  
