#!/bin/sh
# bvlc_reference_caffenet-2017-01-08.pkl
./train.py \
    --initial_model_path /home/ubuntu/data/models/chainer/bvlc_reference_caffenet/bvlc_reference_caffenet.pkl \
    --root_dir_path      /home/ubuntu/data/devise/selected_images_256 \
    --label_path         /home/ubuntu/data/devise/selected_images_256/label.txt \
    --training_data_path /home/ubuntu/data/devise/selected_images_256/train_valid_.txt \
    --testing_data_path  /home/ubuntu/data/devise/selected_images_256/test_.txt \
    --gpu 0 \
    --epoch 10 \
    --batch_size 314 \
    --test_batch_size 200 \
    --test_interval 217 \
    --out_dir_path       /home/ubuntu/results/devise \
    --mean_image_path    /home/ubuntu/libs/caffe-master/python/caffe/imagenet/ilsvrc_2012_mean.npy
