#!/bin/sh

./create_total_list_by_accuracy.py \
    --selected_class_path /Volumes/TOSHIBA\ EXT/mac/image_net/selected_classes_by_accuracies.txt \
    --src_dir /Volumes/TOSHIBA\ EXT/mac/image_net/selected_images_256_greater_than_200_images
